---
title: ""
author: ""
date: ""
output: 
  pdf_document: 
    includes:
      in_header: preamble.tex
      before_body: frontmatter.tex
    toc: yes
    toc_depth: 3
---

```{r setup, include=FALSE, echo=FALSE}
require("knitr")
opts_knit$set(root.dir = "../")
```

```{r, include=FALSE}
library(magrittr)

list.files() %>% 
  {.[!grepl(pattern = ".", x = ., fixed = TRUE)]} %>% 
  setdiff('book') %>%
  lapply(function(ith_dir) {
    c(paste0("## ", ith_dir, "\n"), 
      unlist(lapply(list.files(path = paste0("./", ith_dir), full.names = TRUE), function(ith_file) {
      all_lines <- readLines(ith_file) # %>% stringi::stri_encode(from = "WINDOWS-1252", to = "UTF-8")
      
      c(sub("#", "###", all_lines[1]), sub("#", "####", all_lines[-1]))
    }), use.names = FALSE), "\n\\pagebreak\n")
  }) %>% 
  unlist(use.names = FALSE) %>% 
  writeLines(con = "book/all-abstracts.md")

```

# Introduction

The purpose of Why R? is to provide the space for the professional networking and knowledge exchange, between practitioners and students, from the area of statistical machine learning, programming, optimization and data science fields.

# List of presentations

```{r, child="all-abstracts.md"}
```


